background_color: [64, 64, 64]
question_file: "/data/CLEVR_questions.json"
masks_path: "/data/masks/"
scenes_path: "/data/scenes/"
# If ground_truth_path is given as a directory,
# Then each ground truth is saved seperately
ground_truth_path: "/data/ground_truth/"
# or
#ground_truth_path: "/data/ground_truth.npy"

# Change below for each method
pred_file: "/data/predictions/pred.json"
heatmap_path: "/data/heatmaps/lrp/"
heatmap_shape: [128, 128]
# change to true if you need the ground truth to contain all objects
target_all: False
